### ISSUE TITLE
[Labs 23 READ THIS FIRST] Current Deployment Status 

### ISSUE THREAD

**Issue by mvkumar14** [Lambda-School-Labs/betterreads-ds#11]
The DS API is currently deployed from a personal heroku account. A team heroku account has been set up, but code has not been deployed from there yet, due to access permissions regarding 

You can :
1) Keep the current setup and explore a docker deployment 
OR
2) Set up with the team heroku account deploying from this (betterreads-ds) repo. This requires setting up a github for the team betterreadlabs21@gmail.com account, and giving that account admin privelages to this repo, OR having a TL or SL deploy the app using their admin privelages, OR designating one team member to deploy with admin privelages from their personal github. Work this out with your TL/SL.

The advantage of the second option is that you can quickly upload and test new code. I (personally) don't know enough about docker to say how long docker deployment will take, but the docker solution might be better for the long term. ([See issue #8](https://github.com/Lambda-School-Labs/betterreads-ds/issues/8))

To access the betterreadslabs21 heroku account you MUST sign in using the google sign in, and not a e-mail password combination. You can either deploy to the existing dyno from a personal repo, or you can request admin access to the Lambda-School-Labs/betterreads-ds repo using the betterreadsdslabs21@gmail.com account, and then deploy from the heroku_deployment branch 

Note here that one of the environment (otherwise known as config variable) variables that has to be set to deploy properly is the GOOGLE_KEY. The current dyno in the heroku account already has this variable set (with an API key associated with the betterreadslabs21 gmail account), but if you want to deploy in a new environment the GOOGLE_KEY variable has to be set. 

Google API keys can be found:
https://console.cloud.google.com/apis/dashboard (signing in with the gmail account)

**Comment by michael-rowland** [comment]
We have successfully deployed to AWS Elastic Beanstalk, and do not anticipate using Heroku.
