### ISSUE TITLE
Refactoring: Recommendation Engine

### ISSUE THREAD

**Issue by michael-rowland** [Lambda-School-Labs/betterreads-ds#22]
**The recommendation engine should be isolated to it's own file and class.** 

This would eliminate data processing from within the API (routes) file, and make our code generally more readable. This would also mean development and iteration on the recommendation engine would be contained to the recommendation file.

When we serve our recommendations, we would simply call the recommendation class with our input data and return our recommendations.

https://github.com/Lambda-School-Labs/betterreads-ds/blob/2496f95424cedcce8512c7d476017ab818698944/readrr_api/routes/recommendations.py#L37

**Comment by jose-marquez89** [comment]
There's a duplicate of this function in the gb_funcs.py file. We could move this out of the script with the recommendation route and replace the outdated one in the module.

**Comment by michael-rowland** [comment]
This has been implemented here:
https://github.com/Lambda-School-Labs/betterreads-ds/blob/1e2d328b375f0b3e5ef4c14dcc8c27a3fd365492/readrr_api/route_tools/recommender.py#L50
