### ISSUE TITLE
Open Library Data Cleaning + Upload to AWS RDS

### ISSUE THREAD

**Issue by mvkumar14** [Lambda-School-Labs/betterreads-ds#5]
The OpenLibrary data is largely unusable for the following reason: the works and editions contain entries that are not informative / are garbage data. This is caused by bots creating duplicate 'works' and 'editions' entries in the original OpenLibrary data that have mostly null values except for small changes, such as a different publisher or description. 

However, there is a solution to this issue. The editions data entries contain the text array labeled 'Works' which has a link/key to the work that the edition is supposed to be associated with. You can use this information to eliminate "garbage" entries in the works table.

See this branch for more details, and some of the work that has been done with the OpenLibrary API and AWS RDS database: https://github.com/Lambda-School-Labs/betterreads-ds/tree/database-management/Database-management

Here is the trello card associated with this issue: https://trello.com/c/RMeNuIes

**Comment by michael-rowland** [comment]
We have deployed our database with Goodbooks and Google Books data to AWS RDS
