### ISSUE TITLE
Improve Recommendations 

### ISSUE THREAD

**Issue by mvkumar14** [Lambda-School-Labs/betterreads-ds#6]
Right now recommendations are Hardcoded into the Heroku endpoint. See the deployment issue () for more details on why we switched to Heroku in the last few days of the project, as well as why we have a hardcoded endpoint. 

Setting aside deployment issues; recommendations can improve in two distinct ways:

1) Allow the model to take in any book, and output a list of recommendations based on: 
    a) the top 10,000 books, and/or 
    b) every book (dependent on status of OpenLibrary Data)
These two options (a and b) for improving the model in this way can be worked on concurrently, or sequentially.

2) Add data to the model to "improve" recommendations. Possible sources of data are listed here: https://trello.com/c/sxs8x9zJ. Check out existing branches for some starter code, and feel free to extend the branches, or create your own to add to the AWS database.

The trello card associated with this issue can be found here: https://trello.com/c/2XJQPkRi

**Comment by michael-rowland** [comment]
We have deployed a hybrid model that combines recommendations based on the user rated books, as well as the content based recommendations based on a book's description.
