### ISSUE TITLE
Metric to evaluate recommendations

### ISSUE THREAD

**Issue by mvkumar14** [Lambda-School-Labs/betterreads-ds#7]
There is currently no metric to evaluate the quality of recommendations, so you will have to get a sense for how "good" the recommendations are based on how people react to the recommendations.

We need to set up a framework for A/B testing models with users. We want the framework to be ready when the app has users, so iteration can be done quickly.

**Comment by michael-rowland** [comment]
We have developed rough user surveys to evaluate model performance. This is still a work in progress, and an area for future development.
