### ISSUE TITLE
Deployment on Docker

### ISSUE THREAD

**Issue by mvkumar14** [Lambda-School-Labs/betterreads-ds#8]
The team had to switch from deployment on AWS to deployment on Heroku in the last few days of the project due to CORS issues. The current AWS solution launches a Flask app. These CORS issues may be resolved by using an AWS elastic beanstalk instance launching a docker container. Look into the docker solution, to deploy the recommendation model.

Here are the options:

**Heroku**
Pros: CORS is functioning properly
Cons: Filesize issue (data must be uploaded to the central repository before recommendation models can function). Also admin privileges to Lambda-School-Labs/betterreads-ds are required to deploy from the [heroku_deployment](https://github.com/Lambda-School-Labs/betterreads-ds/tree/heroku_deployment) branch 

**AWS Flask**
Pros: You don't have to worry about filesize
Cons: CORS doesn't work

**AWS Docker**
This seems to be the best solution. You can upload large files if needed, and in the long term code can be refactored to access the central database.

**Comment by michael-rowland** [comment]
Successfully deployed using AWS Elastic Beanstalk. Will consider using a Docker container in future releases.
